=== LorenaCapo/XML_Schemas/eDreams/edreams.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.edreams.com" 
		xmlns:ed="http://www.edreams.com" 
		elementFormDefault="qualified">

	<xsd:import namespace="http://www.iata.com/wac"
		schemaLocation="IATA/IATA.xsd">
	</xsd:import>
	<xsd:include schemaLocation="edreamsSimples.xsd"></xsd:include>

<!-- ComplexType -->
		<xsd:element name="booking" type="ed:booking">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element maxOccurs="unbounded" name="flyTicket" type="ed:flyTicketType"></xsd:element>
				</xsd:sequence>
			</xsd:complexType>
		</xsd:element>
		
		<xsd:complexType name="flyTicketType">
			<xsd:sequence>
				<xsd:element name="journey" type="ed:journeyType"></xsd:element>
				<xsd:element name="data" type="ed:dataType"></xsd:element>
				<xsd:element name="traveller" type="ed:travellerType"></xsd:element>
				<xsd:element name="class" type="ed:classType"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		
		<xsd:complexType name="journeyType">
			<xsd:sequence>
				<xsd:element name="from" type="ed:tWAC"></xsd:element>
				<xsd:element name="to" type="ed:tWAC"></xsd:element>
				<xsd:choice>
					<xsd:element name="ida">
						<xsd:complexType></xsd:complexType>
					</xsd:element>
					<xsd:element name="idaYVuelta">
						<xsd:complexType></xsd:complexType>
					</xsd:element>
					<xsd:element name="multidestino">
						<xsd:complexType></xsd:complexType>
					</xsd:element>
				</xsd:choice>
				<xsd:element name="from" type="xsd:string"></xsd:element>
				<xsd:element name="to" type="xsd:string"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		
		<xsd:complexType name="dataType">
			<xsd:sequence>
				<xsd:element name="dataFrom" type="xsd:date"></xsd:element>
				<xsd:element name="dataTo" type="xsd:date"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		
		<xsd:complexType name="travellerType">
			<xsd:sequence>
				<xsd:element name="adults" type="ed:travellerAdults"></xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="kids" type="ed:travellerKids"></xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="baby" type="ed:travellerBaby"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		
		<xsd:complexType name="tWAC"> <!--  World Airport Code segun IATA -->
				<xsd:simpleContent>
					<xsd:extension base="xs:string">
						<xsd:attribute name="WAC" type="ed:WAC"></xsd:attribute>
					</xsd:extension>
				</xsd:simpleContent>
		</xsd:complexType>
		
		
		
		<xsd:complexType name="extTravellerType">
		<xsd:complexContent>
			<xsd:extension base="ed:travellerType">
				<xsd:sequence>
					<xsd:element name="animals" type="xs:integer"></xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="extTravellerPackageType">
		<xsd:complexContent>
			<xsd:extension base="ed:travelleType">
				<xsd:sequence>
					<xsd:element name="bicycle" type="xs:integer" minOccurs="0"></xsd:element>
					<xsd:element name="instruments" type="xs:integer" minOccurs="0"></xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
		

</xsd:schema>

=== LorenaCapo/XML_Schemas/eDreams/edreams.xml
<?xml version="1.0" encoding="UTF-8"?>
<ed:booking 
xmlns:ed="http://www.edreams.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.edreams.com edreams.xsd">
	<ed:flyTicket>
		<ed:journey>
			<ed:idaYVuelta />
			<ed:from WAC="PMI">Palma de Mallorca (PMI)</ed:from>
			<ed:to WAC="BCN">Barcelona (BCN)</ed:to>
		</ed:journey>
		<ed:data>
			<ed:dataFrom>2016-03-15</ed:dataFrom>
			<ed:dataTo>2016-03-30</ed:dataTo>
		</ed:data>
		<ed:traveller>
			<ed:adults>1</ed:adults>
			<ed:kids>1</ed:kids>
			<ed:baby>0</ed:baby>
		</ed:traveller>
		<ed:class>turista</ed:class>
	</ed:flyTicket>
</ed:booking>
